### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by knkrth** [dashed-slug/wallets#1]
Everything works fine in the wordpress preview but when I publish and visit the link it doesn't show Coin addresss, So on. Can you help me with that? Here is the wordpress link http://13.59.125.11/wp/index.php/wallet/

**Comment by alex-georgiou** [comment]
Hello,

I do not offer support over GitHub as this is simply a mirror repo, so people can view the code. I will modify the readme to make this more clear.

Support is offered at https://wordpress.org/support/plugin/wallets and over email at info@dashed-slug.net

Your particular issue is addressed in the troubleshooting section of the manual. The manual is available in the bundle download available from the Download section of the site https://dashed-slug.net/downloads

regards,
Alex
